
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY="genevieve_usher_group_construction_demo_v1";
const letterText="GENEVIEVE App\u2122 \u2014 Usher Group Construction Site Flow & Safety Support Assistant\nDEMO ONLY \u2014 fake data only\n\nPurpose:\nThis demo has been built to show how GENEVIEVE App\u2122 could support Usher Group-style construction, painting, waterproofing, supervisors, subcontractors and site managers.\n\nIt is not designed to replace workplace health and safety systems, site supervisors, qualified trades, engineers, inspectors, certifiers, legal advisers or insurance advisers.\n\nIt is designed to sit beside the work and make risks, missed checks, fatigue, defects, materials, handovers and sign-offs visible before they become bigger problems.\n\nWhat this first construction demo shows:\n- daily site check-in\n- worker break and fatigue check\n- site hazard board\n- weather and surface condition checks\n- painting module\n- waterproofing module\n- materials and stock alerts\n- defect photo log\n- rework risk alerts\n- supervisor sign-off\n- subcontractor handover\n- manager action board\n- evidence export\n- legal/safety wording boundaries\n\nThe Genevieve colour system:\nGREEN \u2014 ready, checked, covered, stable\nAMBER \u2014 check soon, caution, support or review needed\nRED \u2014 do not proceed, action required, supervisor review needed\nBLACK / URGENT \u2014 immediate safety pathway or stop-work escalation\n\nThis demo uses fake data only.\nDo not enter real site incidents, real worker information, confidential builder data or live client information until the system has had proper legal, WHS, privacy, insurance and business review.\n\nCreated by Tracey Kennedy\nGENEVIEVE App\u2122\nCreated: 2026-07-11\n";
let state={logs:[]};
const sites=[{name:"Usher Group Demo Apartment Site",supervisor:"Site Supervisor A",status:"amber",reason:"Weather and waterproofing cure time need review."},{name:"Usher Group Demo Fitout Site",supervisor:"Site Supervisor B",status:"green",reason:"Checks complete. Painting ready."}];
const workers=[{id:"w1",name:"Painter 1",role:"Painter",hours:5.5,heat:"Medium",status:"amber",task:"Surface prep and primer"},{id:"w2",name:"Waterproofer 1",role:"Waterproofer",hours:7,heat:"High",status:"red",task:"Wet area membrane"},{id:"w3",name:"Apprentice 1",role:"Apprentice",hours:3,heat:"Low",status:"green",task:"Material run and masking"},{id:"w4",name:"Supervisor A",role:"Supervisor",hours:6,heat:"Medium",status:"amber",task:"Sign-offs and handovers"}];
const hazards=[{title:"Open penetration near wet area",area:"Level 4 bathroom",status:"red",action:"Cover/exclusion and supervisor review before waterproofing continues."},{title:"Paint fumes / ventilation check",area:"Basement corridor",status:"amber",action:"Confirm ventilation and PPE before coating."},{title:"Trip hazard - materials stacked near access",area:"Entry path",status:"amber",action:"Move materials and keep emergency access clear."}];
const materials=[{item:"Waterproofing membrane",qty:2,min:5,status:"red",action:"Order today. Do not start new area without confirmed stock."},{item:"Primer sealer",qty:7,min:4,status:"green",action:"Enough for current work."},{item:"Low VOC paint",qty:3,min:4,status:"amber",action:"Check next delivery before afternoon coat."},{item:"Masking tape",qty:12,min:6,status:"green",action:"Enough stock."}];
const defects=[{title:"Pin holes in membrane",trade:"Waterproofing",status:"red",cost:"High rework risk",action:"Stop, photo, repair, recheck coat thickness."},{title:"Uneven sanding visible",trade:"Painting",status:"amber",cost:"Medium rework risk",action:"Fix prep before primer."},{title:"Missing photo proof before cover-up",trade:"General",status:"red",cost:"Insurance/evidence risk",action:"Take photos and supervisor sign-off before closing."}];
const handovers=[{from:"Waterproofing",to:"Tiling",status:"red",action:"Flood test and photo proof missing."},{from:"Painting prep",to:"Primer coat",status:"amber",action:"Dust clean confirmation needed."}];
const siteChecks=["Site access clear","Emergency access clear","PPE available","Exclusion zones checked","Weather checked","Surface conditions checked","Materials confirmed","Workers briefed","Break plan confirmed","Hazards reviewed","Supervisor sign-off"];
const waterproofChecks=["Substrate clean and sound","Falls checked","Moisture checked","Primer applied","Corners/tapes/penetrations sealed","Membrane coat 1 complete","Cure time confirmed","Membrane coat 2 complete","Dry film thickness checked","Flood test / water test recorded","Photo proof saved","Supervisor sign-off"];
const paintingChecks=["Surface sanded","Dust removed","Moisture/surface checked","Primer correct for surface","Coat product recorded","Drying time confirmed","Ventilation checked","Defects checked between coats","Colour confirmed","Final coat inspected","Photo proof saved","Supervisor sign-off"];
const handoverChecks=["Previous trade complete","Photos attached","Defects closed","Materials cleared","Access safe","Next trade briefed","Supervisor sign-off","Evidence exported"];
const dbSections=[["Sites","Site ID, site name, supervisor, active trades, site status."],["Workers","Worker ID, role, fatigue check, break status, task assignment."],["Daily Site Checks","Weather, access, hazards, PPE, emergency access, sign-off."],["Hazards","Type, location, photo, severity, owner, due time, closed time."],["Waterproofing","Substrate, moisture, primer, membrane stages, curing, flood test, photo proof."],["Painting","Prep, primer, coats, drying time, weather/ventilation, defects, sign-off."],["Materials","Quantity, minimum level, supplier, expiry/shelf life, reorder alert."],["Defects / Rework","Defect, trade, severity, cause, action, close-out evidence."],["Handovers","From trade, to trade, checklist, photos, supervisor sign-off."],["Evidence Log","Photos, checklists, timestamps, signatures, exports and audit trail."]];
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){};state.logs=state.logs||[];save()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function go(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");$$(".bottom button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));render();scrollTo({top:0,behavior:"smooth"})}
function tag(s){return `<span class="tag ${s}">${String(s).toUpperCase()}</span>`}
function item(o){return `<article class="item ${o.status}"><h4>${o.title||o.name||o.item||o.from+" → "+o.to}</h4>${tag(o.status)}<p>${o.reason||o.action||""}</p>${o.area?`<p><b>Area:</b> ${o.area}</p>`:""}${o.trade?`<p><b>Trade:</b> ${o.trade} • <b>Risk:</b> ${o.cost}</p>`:""}</article>`}
function render(){renderHome();renderSites();renderWorkers();renderHazards();renderChecklists();renderMaterials();renderDefects();renderHandovers();renderManager();renderDB();$("#letterText")&&($("#letterText").textContent=letterText)}
function renderHome(){let reds=[...sites,...workers,...hazards,...materials,...defects,...handovers].filter(x=>x.status==="red").length;$("#statSites").textContent=sites.length;$("#statWorkers").textContent=workers.length;$("#statRed").textContent=reds;$("#statStock").textContent=materials.filter(m=>m.status!=="green").length}
function renderSites(){if(!$("#siteList"))return;$("#siteList").innerHTML=sites.map(item).join("")}
function renderWorkers(){if(!$("#workerList"))return;$("#workerList").innerHTML=workers.map(w=>`<article class="item ${workerStatus(w)}"><h4>${w.name}</h4>${tag(workerStatus(w))}<p><b>${w.role}</b> • ${w.hours} hours worked • heat ${w.heat}</p><p><b>Task:</b> ${w.task}</p><p><b>Break finished:</b> ${last(w.name,"Break finished")?"Yes":"Not recorded"}</p></article>`).join("");let sel=$("#workerSelect");if(sel){let cur=sel.value;sel.innerHTML=workers.map(w=>`<option value="${w.id}">${w.name}</option>`).join("");if(cur)sel.value=cur}renderLogs()}
function workerStatus(w){if(last(w.name,"Fatigue / heat stress")||last(w.name,"Support needed"))return"red";if(!last(w.name,"Break finished")||w.status==="amber")return"amber";return w.status}
function last(name,type){return state.logs.find(l=>l.worker===name&&l.type===type)}
function log(type){let id=$("#workerSelect").value;let w=workers.find(x=>x.id===id)||workers[0];state.logs.unshift({time:new Date().toLocaleString(),worker:w.name,type});save();render()}
function renderLogs(){if(!$("#workerLog"))return;$("#workerLog").innerHTML=state.logs.length?state.logs.slice(0,20).map(l=>`<article class="item green"><h4>${l.worker}</h4><p>${l.type} • ${l.time}</p></article>`).join(""):"<p>No worker clicks yet.</p>"}
function renderHazards(){if(!$("#hazardList"))return;$("#hazardList").innerHTML=hazards.map(item).join("")}
function renderChecklists(){let fill=(id,arr)=>{let el=$("#"+id);if(el)el.innerHTML=arr.map(x=>`<label class="check"><input type="checkbox"><span>${x}</span></label>`).join("")};fill("siteChecklist",siteChecks);fill("waterproofChecklist",waterproofChecks);fill("paintingChecklist",paintingChecks);fill("handoverList",handoverChecks);if($("#waterproofAlerts"))$("#waterproofAlerts").innerHTML=defects.filter(d=>d.trade==="Waterproofing").map(item).join("");if($("#paintingAlerts"))$("#paintingAlerts").innerHTML=defects.filter(d=>d.trade==="Painting").map(item).join("")}
function renderMaterials(){if(!$("#materialList"))return;$("#materialList").innerHTML=materials.map(m=>`<article class="item ${m.status}"><h4>${m.item}</h4>${tag(m.status)}<p><b>Qty:</b> ${m.qty} • <b>Minimum:</b> ${m.min}</p><p>${m.action}</p></article>`).join("")}
function renderDefects(){if(!$("#defectList"))return;$("#defectList").innerHTML=defects.map(item).join("")}
function renderHandovers(){if(!$("#openHandovers"))return;$("#openHandovers").innerHTML=handovers.map(item).join("")}
function renderManager(){if(!$("#managerList"))return;let actions=[...sites,...workers.map(w=>({...w,status:workerStatus(w),title:w.name,action:w.task})),...hazards,...materials,...defects,...handovers].filter(x=>x.status!=="green");$("#managerList").innerHTML=actions.map(item).join("");let patterns=[];if(materials.some(m=>m.status==="red"))patterns.push({status:"red",title:"Stock risk pattern",action:"Critical material is below minimum before work stage."});if(workers.some(w=>workerStatus(w)!=="green"))patterns.push({status:"amber",title:"Worker support pattern",action:"Breaks/fatigue/support clicks should be reviewed before overtime or high-risk tasks."});if(defects.some(d=>d.status==="red"))patterns.push({status:"red",title:"Rework risk pattern",action:"Red defects are linked to missing proof or stage quality checks."});$("#learnedList").innerHTML=patterns.map(item).join("")}
function renderDB(){if(!$("#dbSections"))return;$("#dbSections").innerHTML=dbSections.map(d=>`<div class="db-table"><b>${d[0]}</b><span>${d[1]}</span></div>`).join("")}
function csv(rows,fields){let esc=v=>`"${String(v??"").replace(/"/g,'""')}"`;return [fields.join(","),...rows.map(r=>fields.map(f=>esc(r[f])).join(","))].join("\\n")}
function dl(name,text,type="text/plain"){let b=new Blob([text],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}
document.addEventListener("click",e=>{let s=e.target.closest("[data-screen]");if(s)go(s.dataset.screen)});
document.addEventListener("DOMContentLoaded",()=>{load();render();$("#breakStart").onclick=()=>log("Break started");$("#breakFinish").onclick=()=>log("Break finished");$("#fatigue").onclick=()=>log("Fatigue / heat stress");$("#support").onclick=()=>log("Support needed");$("#taskDone").onclick=()=>log("Task complete");$("#downloadLetter").onclick=()=>dl("Usher_Group_Construction_Demo_Description.txt",letterText);$("#exportActions").onclick=()=>{let actions=[...sites,...hazards,...materials,...defects,...handovers].filter(x=>x.status!=="green").map(x=>({name:x.title||x.name||x.item||(x.from+" to "+x.to),status:x.status,action:x.action||x.reason}));dl("usher_group_construction_actions.csv",csv(actions,["name","status","action"]),"text/csv")};$("#exportWorkers").onclick=()=>dl("usher_group_workers.csv",csv(workers,["id","name","role","hours","heat","status","task"]),"text/csv");$("#exportMaterials").onclick=()=>dl("usher_group_materials.csv",csv(materials,["item","qty","min","status","action"]),"text/csv");$("#exportLogs").onclick=()=>dl("usher_group_worker_logs.csv",csv(state.logs,["time","worker","type"]),"text/csv")});
